### ISSUE TITLE
Tags do not update and do not work anymore (#1176) is unsolved

### ISSUE THREAD

**Issue by mockinbirdy** [streetwriters/notesnook#1196]
### What happened?

Hi, I still have these issues with tags. Both problems still occur. 

### Steps to reproduce the problem

Fix it

### Version

web

### Platform/OS

Chrome/Chromium

**Comment by thecodrr** [comment]
We haven't yet released a new version so i am not sure what you are expecting. There is no need to spam the issue tracker with your demands to fix an issue we have already fixed.

Kindly wait with patience until the next release and then comment on the old issue (instead of creating a new one) if the issue hasn't been fixed.
