### ISSUE TITLE
Can't add note to notebook

### ISSUE THREAD

**Issue by altano** [streetwriters/notesnook#18]
**Describe the bug**
I'm trying to add a note to a notebook. The UI is confusing and I can't figure out how to make it work.

**To Reproduce**
1. Create a notebook called "stuff"
2. Click "Notes"
3. Click "..." menu for note => "Add to notebook(s)"
4. Click "stuff"
5. Click "done"

**Expected behavior**
* When clicking the notebook "stuff" a plus mark appears on the right. Does that mean it's selected? No idea. I would expect better feedback here that "stuff" is selected
* The note should be in the notebook but it appears that the notebook is empty

**Screenshots**
https://user-images.githubusercontent.com/1009/127756223-44b9873b-7d12-42cf-9cac-df03416ba905.mp4

**Desktop (please complete the following information):**
* OS: Windows
* Native app
* Version: 1.4.1-781aa6a-web

**Comment by thecodrr** [comment]
Basically, since we removed the default General topic clicking the notebook made it appear empty. If you press the "+" button, it'll create a new topic. After that things appear normal.

This has also been fixed. The new behavior is that opening an empty notebook in the move note dialog, automatically shows the create topic input.
