### ISSUE TITLE
Tray icon not shown in flatpak notesnook

### ISSUE THREAD

**Issue by muznyo** [streetwriters/notesnook#2035]
### What happened?

Before, i used the rpm package, but now i use flatpak because of the convenience.

In rpm packaged version, notesnook tray icon was shown, but after i switched to flatpak packaged version it does not work.

### Steps to reproduce the problem

1. close the app
2. no tray icon, but its still running in background and cant open it again from applications menu

### Version

v2.4.4

### Platform/OS

Linux

### Relevant log output

*No response*

**Comment by muznyo** [comment]
Icon is still not shown.

Showing tray icon in flatpak packaged app is possible, for example bitwarden has tray icon.

**Comment by thecodrr** [comment]
@muznyo It is showing on my end. I have KDE. Unfortunately, there's no single way in flatpak to make it work. It'll be best if you can experiment around with the flatpak manifest and see what works. I can merge the required changes.

**Comment by RayJW** [comment]
I did some research and found some related things like with [Discord](https://github.com/flathub/com.discordapp.Discord/commit/90d9f1a0c350b4d479738476e53fea4bba473a83), [Vencord](https://github.com/flathub/dev.vencord.Vesktop/pull/10/files), or the [GNOME extension](https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/471). It seems like Notesnook needs to set the `TMPDIR` correctly, because otherwise the tray icon is expected to be inside `/tmp` which is obviously not possible due to the Flatpak sandboxing. It would be very nice if this could be fixed :)

**Comment by thecodrr** [comment]
Happy to accept a PR @RayJW since I don't really have a Linux system anymore.

**Comment by RayJW** [comment]
> Happy to accept a PR [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/29835902?s=64&amp;u=15b54d1281bd252ca6b084aaa0444e3d914239bc&amp;v=4">@RayJW](https://github.com/RayJW) since I don't really have a Linux system anymore.

I opened a [PR](https://github.com/flathub/com.notesnook.Notesnook/pull/55) on the Flathub repo that should fix this issue.
