### ISSUE TITLE
Sub topics in notebooks

### ISSUE THREAD

**Issue by fborgo** [streetwriters/notesnook#222]
It would be great if you could down the road, add SUB-TOPICS (deeper in the tree). Only one level is not enough for heavy users.... At least two more levels ... ie.: Notebook > Topic > Sub-Topic > Sub-Sub-Topic > Notes, Notes, ... etc.

**Comment by thecodrr** [comment]
Complex hierarchies are counter-productive that is why Notesnook has a strict organization structure. Having more than 2 layers at first sounds appealing but eventually it becomes just as hard to find a note as if it weren't organized at all. Simple hierarchy is predictable — at any time you know exactly where a note is because the hierarchy can be easily remembered.

I don't think this has anything to do with being a heavy user or not — just preference. In the end, I have found simple but many structures to be more useful over complex but few structures.

**Comment by fborgo** [comment]
I do not agree. Specially NotesNook fails to find searchs from categories. It only finds if on notes side. 
I've been using notes systems for a very long time and with hundreds of categories and am telling from experience.

**Comment by gaganyadav80** [comment]
I also think that any type hierarchy should NOT be imposed. The user should be able to choose how much deep he wants to link his/her notes or maybe not even add a single topic under notebook (notes directly under notebook).

**Comment by thecodrr** [comment]
We are looking into how we can improve the current organization system.

**Comment by McBaumwolle** [comment]
I agree with OP, I tried to switch to Notesnook for my uni notes, but my usual hierarchy did not work as intended. 
notebook [uni] -> topic [semester x] -> topic [math] -> notes
It just got too confusing when I had multiple notebooks for my uni classes and a few for my personal notes, so currently I am using OneNote and Notion for uni because they allow that structure.

**Comment by sharemind** [comment]
It would be nice to have in the Roadmap list a ridefinition of the notes organizational structure to include sub-topic in notebooks.

**Comment by JoshuaACasey** [comment]
> We are looking into how we can improve the current organization system.

a place--probably in the sidebar--to view all "untagged" notes would be very nice.

**Comment by RobLW** [comment]
Would love to see this feature. Happened to be looking at an alternative from Obsidian. I wouldn't agree it is "counter productive" which is why so many use it. No one is forcing a user to have to nest folders/directories, it's just nice to have the option for those of us who do. 
The issue says closed completed, but I couldn't see how/where I can do this.

**Comment by thecodrr** [comment]
This has already landed @RobLW. Right click on any notebook and add a new notebook under it.
