### ISSUE TITLE
Open files and edit them without the need to download and re-upload

### ISSUE THREAD

**Issue by ms-2525** [streetwriters/notesnook#2395]
### What problem are you facing?

Add an option which is available in evernote, upnote, joplin which allows to open the attached files without the need to download them. Like i have an excel sheet which i have attached in notesnook. I want to open the excel sheet, edit it and want the edited sheet to be saved in notesnook.
In above mentioned apps, i have to just attach the file once and every time i need to view or edit the excel sheet, i just have to double click on the attachment and it opens. I can make the changes and when i save the file and close it, the changes are saved in the attached file as well

### What's the solution you'd like to see in Notesnook?

Ability to open the files and update the attachments when changes are made to the attached files automatically

**Comment by thecodrr** [comment]
@ms-2525 thank you for taking the time to suggest this feature. We are working on Attachment Previews which will allow you to open different types of attachments & see them right within the app.

As far as editing goes, that probably won't be supported due to it being overly complex to get right across all platforms.
