### ISSUE TITLE
Feature request for Reminders 

### ISSUE THREAD

**Issue by Madhan-kumar-selvaraj** [streetwriters/notesnook#2667]
### What problem are you facing?

- Foremost, thanks to the NotesNook team, and you guys are doing a wonderful job. I can see the daily commits at the GitHub that shows how hardly you guys are working day and night. 
- I am using the NotesNook 2.5.1 version at web and Android application
- I am using TickTick https://www.ticktick.com application for a year and I felt some features in the TikTick is very useful to use. We can implement those features at the reminder part.

### What's the solution you'd like to see in Notesnook?

1. No options to remind notes/tasks at yearly manner. Ex- Birthday, Anniversary. 
![image](https://github.com/streetwriters/notesnook/assets/59301245/31b11be8-d523-4169-ba9a-628d8b813f95)
2. Issue with the "repeat" reminder. The reminder excluded the current month reminder. Check the below image for reference
![image](https://github.com/streetwriters/notesnook/assets/59301245/1bbfab06-2777-4f5a-91e5-26a39a8beac0)
3. In the TickTick, there is an option to complete the task even before the due date. Also, if the task is completed it'll be moved to the completed menu and next month due date of the task will be there. Check the below screenshot.
![image](https://github.com/streetwriters/notesnook/assets/59301245/d2da7e9c-97d3-4151-b8d0-be59330ee0b5)
4. Need a check radio button to complete the tasks on the reminder, like in TickTick application. 
5. If the above features are there, I'll stop using the TickTick and move to NotesNook for note-taking as well as to remind tasks.

### What alternatives have you considered?

TickTick https://www.ticktick.com application

**Comment by thecodrr** [comment]
Thanks for the feedback.

Let's make a few things clear:

1. Notesnook is not TickTick
2. Reminders are not tasks

Now let's discuss what you are proposing:

1. Yearly reminders are not possible on some platforms (iOS) which is why they aren't included. 
2. Yes, that's a bug. I suggest you create a separate issue for this.
3. Reminders in the past make no sense as they will never activate.
4. Reminders are not tasks. Task lists inside the editor will eventually include the option to set a due date.
