### ISSUE TITLE
Markdown editor option

### ISSUE THREAD

**Issue by McBaumwolle** [streetwriters/notesnook#2677]
### What problem are you facing?

It would be nice to have a toggle for normal & markdown view, so someone could work in markdown and then switch back to the normal editor. 

### What's the solution you'd like to see in Notesnook?

A small dropdown menu in the bar with "normal" and "markdown" options, or a simple checkbox with ".md". 

### Additional context

It would also be great to quickly import a simple .md file as the current importer is great for in-bulk imports but not convenient for like one document. 
https://github.com/streetwriters/notesnook/issues/456 also mentioned this but only on mobile, maybe I am missing the option in the web.

**Comment by thecodrr** [comment]
Raw Markdown editing will not be supported because there are many things we use that just don't translate well in Markdown. Moreover, we have no plans on maintaining 2 editors. The current editor supports all CommonMark Markdown shortcuts which is as far as we are willing to go.

> It would also be great to quickly import a simple .md file

I suggest you open a separate issue for this so it can be discussed properly.
