### ISSUE TITLE
Sync failing when AdGuard is filtering traffic

### ISSUE THREAD

**Issue by muchqs** [streetwriters/notesnook#2729]
### What happened?

Just registered today and I can't sync on my phone that's running Android 9.
Tried on desktop browser, it syncs fine.
Tried on android tablet running Android 11, syncs fine, but editor format like font type is not synced from desktop. why is this?
Then tried on phone with Android 9, after log in, it says "please wait while we sync all your data" and it never completes. The progress bar is stuck at like 10% forever. I have tried log out and back in. Force sync. Clear app cache and data. etc.

Clicking on the sync button at bottom left corner of the app literally does nothing for some reason. Tap on it and nothing happens at all.

https://i.imgur.com/v4T8JyZ.jpg

### Steps to reproduce the problem

1. log in on Android 9
2. it says "please wait while we sync all your data"
3. stuck forever

### Version

2.5.2 from F-Droid

### Platform/OS

Android

**Comment by ammarahm-ed** [comment]
Hey, 

> editor format like font type is not synced from desktop. why is this?

Font family & font size settings are not synced between devices.

> Then tried on phone with Android 9, after log in, it says "please wait while we sync all your data" and it never completes. The progress bar is stuck at like 10% forever. I have tried log out and back in. Force sync. Clear app cache and data. etc.

> Clicking on the sync button at bottom left corner of the app literally does nothing for some reason. Tap on it and nothing happens at all.

Okay, can you take these steps:

1. Login  on your phone,
2. When it get's stuck at 10%, wait a minute or two then relaunch the app.
3. It should start syncing your notes in background automatically and your notes should appear.

If you don't see your notes even then, do the following

1. Go to app settings
2. Scroll down to "Help and Support" and click on "Debugging > Debug Logs"
3. Download the logs and send them here so we can take a look.


I will also test on and android 9 device to see what might be the problem here.

**Comment by thecodrr** [comment]
I will have to test Notesnook with AdGuard to see if it happens on my end or not. I have Android 13.

I think the problem is with the WebSocket connection failing to establish.

**Comment by thecodrr** [comment]
@muchqs since this is not an issue with Notesnook but Adguard, there's very little we can do.
