### ISSUE TITLE
Bun and Tauri or Dart-flutter usage?

### ISSUE THREAD

**Issue by sim4life** [streetwriters/notesnook#3434]
### What problem are you facing?

Less responsive interface

### What's the solution you'd like to see in Notesnook?

Usage of newer libraries/frameworks like Bun (bun.sh), Tauri or Dart-Flutter are expected to provide more responsive and lightweight interface to the end user 

### What alternatives have you considered?

Obsidian, Outline (getoutline), AppFlowy, Joplin, Notable

### Additional context

Time to load, search, organise notes and notebooks get affected in electron apps. Moreover, Electron apps tend to intermittently black out (crash) on macOS and other OSes without notice for some new app release. Electron apps are also very slow responsive on mobile OSes.

**Comment by thecodrr** [comment]
Please provide specific examples of where you have noticed "less responsiveness" in Notesnook otherwise this issue sounds like you are trolling and wasting everyone's time.

> like Bun (bun.sh), 
Bun is a Javascript Runtime like NodeJS. I do not see what that has to do with Notesnook.

> Tauri

Tauri is not mature enough to be considered. The only thing it can do close to well is open windows & render HTML. Notesnook requires a lot more than that.

> Dart-Flutter 

Dart is slower than JS on many levels. And we have no plans to waste time rewriting things. That'd be incredibly stupid of everyone involved.

> Electron apps are also very slow responsive on mobile OSes.

Electron does not run on mobile OSes. What are you talking about?

> Electron apps tend to intermittently black out (crash) on macOS and other OSes without notice for some new app release

That has nothing to do with Electron. Any app can black out and crash.

Frankly speaking, you have no idea what you are talking about.
