### ISSUE TITLE
Math & formula feature in NN hides some part of text on Android.

### ISSUE THREAD

**Issue by Starship-Headlight** [streetwriters/notesnook#3531]
### What happened?

There was a scrollbar issue with Math & Formula feature that was fixed in update 2.6.7 and it removed the scrollbar in web app.

But the update missed this bug in the Android app.

### Steps to reproduce the problem

in math & formula type 

s = \frac{6+6+6}{2} = 9

The editor hides upper part of the 6+6+6.

![6](https://github.com/streetwriters/notesnook/assets/142043604/8e1eac0d-b728-4ed5-8098-4f2e671dff85)

### Version

2.6.7

### Platform/OS

Android

**Comment by abhinav700** [comment]
@Starship-Headlight Hi, I am a beginner and didn't quite understand what problem you are facing.

Can you please explain in more detail?

As far as I understand, Your issue is that no:s are not completely visible in this app when using Math and Formula, and it is Related to scroll bar. Am I correct?

**Comment by Starship-Headlight** [comment]
@abhinav700 You are correct. The developers had recently issued a fix for this but they missed this in android app. I think it works well in desktop and web app but in android it still hides text.
