### ISSUE TITLE
The background color comes when the paragraph is copied and pasted

### ISSUE THREAD

**Issue by muhammadshakkeerp** [streetwriters/notesnook#4162]
### What happened?

The background color comes when the paragraph is copied and pasted from other sources. 

### Steps to reproduce the problem

https://github.com/streetwriters/notesnook/assets/121001685/880fe06a-518e-4776-a2fa-07e4862ef3ba

### Version

v2.6.14

### Platform/OS

Windows

**Comment by thecodrr** [comment]
This is hard to fix because we try to preserve all styles when you paste into the editor. The problem with removing the background color is that sometimes the background color _is_ needed (e.g. in the case of highlighted text). The best workaround for this is to use "Paste without formatting" or simply remove the background color after pasting.
