### ISSUE TITLE
More types of notes

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#423]
**Feature Request**

![tempFileForShare_20220318-200059](https://user-images.githubusercontent.com/51019003/159100618-840ab196-a780-4078-84ca-dcf558b57d79.jpg)

This is inspired by Quillnote. The ability to upload all kinds of media and have it saved in your notes. This would include audio notes, straight images as shown in the screenshot above, regular notes, and perhaps tasks (unless you would want to make that a Notebook template). As for the process of uploading this media, you should be able to choose what you would like to upload after clicking the new note `+` button, and this should include web clippings as well.

**Comment by thecodrr** [comment]
I think one of the best things about Notesnook is the single editor approach instead of having a different editor/note for different kinds of things. For example, you can add task lists, images, attachments, PDFs, etc. all inside a single note or separately. This also helps us in development because we don't have to maintain multiple kinds of editors. For the users, this ensures flexibility as they can choose to add what they want or add something else to an older note whenever they like.

I am closing this as "won't fix" because I don't think this fits into how Notesnook works.
