### ISSUE TITLE
Grid View

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#430]
**Feature Request**

This is an addition more or less to #423. This is an example of what I mean:

![tempFileForShare_20220318-200059](https://user-images.githubusercontent.com/51019003/159100618-840ab196-a780-4078-84ca-dcf558b57d79.jpg)

You can have list view (which is the current default), and gallery mode or whatever you wanna call it.

**Comment by thecodrr** [comment]
You mean grid view. I am not in support of this. Grid view doesn't improve anything in any way - it shows about the same amount of items, the text in the description is also about the same. I don't really see why this view would be preferred unless there was a real use to it.

**Comment by candroid-man** [comment]
The use case is for when/if #423 becomes a reality. So it can show all the types of notes in a nice looking format

**Comment by candroid-man** [comment]
Of course, I know that, but there are things you can do to smoothen the transition. Some people also prefer that look, and I think it would be worth adding

**Comment by candroid-man** [comment]
@thecodrr Add it to the Suggested Features on the website?

**Comment by thecodrr** [comment]
Will do.

**Comment by gaganyadav80** [comment]
For a handful amount of notes this will look good but as the count increase (which will happen) it will take more space on the screen and will make it difficult to navigate to notes by scrolling. 

I think that Evernote does this in a better way ( not just because I like it) because that design increases the note's tile height by less amount compared to grid view and it can show the media on the right side and the note tile and content on the left side (maybe in 3:4 ratio). The amount of height increased in the note's tile can also be used to add some padding between the note content and date-time displayed. ( see #387 ).

**Comment by thecodrr** [comment]
Added to the Suggested Features list

**Comment by thecodrr** [comment]
Closing this as "won't fix" because:

1. The number of votes for this feature/idea have been really low, compared to how long it has stayed on the ideas list (over a year): https://notesnook.com/roadmap/
2. I am personally not keen on adding a grid view for notes as it doesn't really increase UX in any way aside from preference. It also takes up more space reducing the amount of notes you see on a single screen.
