### ISSUE TITLE
Notes published on monogr.ph have formatting issues

### ISSUE THREAD

**Issue by Parthiv-M** [streetwriters/notesnook#4354]
### What happened?

I copied and pasted text from an external website to a new note and published the note. The note published on monogr.ph has formatting issues.

### Steps to reproduce the problem

Here is what I did

* Copied text from [here](https://www.lipsum.com/) and pasted it in a new note

  ![image](https://github.com/streetwriters/notesnook/assets/57034486/e7d94d63-78d1-4789-b271-3c446f10aec2)
* Published the note and got my [monogr.ph URL](https://monogr.ph/65dcf9327171711a34c5c619/)
* Opened the URL in a new tab. By default, it opens in dark mode and there is a white highlight on the text. If formatted text is copied and pasted into the note (as I tried later), the formatting is preserved and there is no highlight, as in the second paragraph of the published note.

  ![image](https://github.com/streetwriters/notesnook/assets/57034486/9d5ad1dd-81f3-4c78-86af-e1b076eaf165)

P.S. Had this issue even when I copied and pasted from Google Docs

### Version

2.6.15-aa730b5-web

### Platform/OS

Chrome/Chromium

### Relevant log output

*No response*

**Comment by ammarahm-ed** [comment]
Hi, I think this is normal since you pasted the text, it has some hidden formatting on the text which you will have to remove manually using the clear formatting button in the toolbar.
 
![Screenshot 2024-02-28 at 18 05 51](https://github.com/streetwriters/notesnook/assets/40239442/823a55b9-20e0-4c54-a4b0-87443bbace6c)

**Comment by Parthiv-M** [comment]
Right, but when I copy paste normal, non-formatted text from, say, Google Docs, I still get [this monograph](https://monogr.ph/65df9648919191c1808c8c8e/)

The text I copied
![image](https://github.com/streetwriters/notesnook/assets/57034486/9c6e494f-21a4-4080-8ba6-4bec82bc46f7)

**Comment by iblazhko** [comment]
This issue is not specific to monograph publishing.

Copy any block of text from a web page, and insert it into a note - you may have exact same issue in the "regular" (non-published) note.

![Screenshot 2024-03-18 075507](https://github.com/streetwriters/notesnook/assets/87576/1f6953d4-660b-4d9a-9643-fd59aca6fa60)

Web clipper does not have this problem, so maybe Notesnook should run a basic style cleanup when pasting HTML into a note, using same rules as in the web clipper.
