### ISSUE TITLE
Tab to indent

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#443]
**Feature Request**

Currently, Tab cycles through all the buttons in the app, when it could be used to do simple indentations like most other text editors.

**Comment by JLuc** [comment]
This github issue textarea has the same "move focus" behaviour when kbd TAB is pressed, as opposed to an "insert TAB in text" behaviour. 
But this github issue textarea is only 4 lines high when first entered, because its not meant to get long structured text.
Notesnook notes appear full screen and are meant to hold long structured text.
I was also surprised and quite upset when i couldnt use TAB to insert a TAB.
