### ISSUE TITLE
Grid layout in All notes section

### ISSUE THREAD

**Issue by ifajul89** [streetwriters/notesnook#6699]
### What problem are you facing?

List style notes style is not good for finding the desired note

### What's the solution you'd like to see in Notesnook?

It would be so great to have the notes organized in a Grid fashion

### What alternatives have you considered?

*No response*

### Additional context

*No response*

<sub><a href="https://huly.app/guest/streetwriters?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzBkMGIzM2RkOThmNGIzNTk2ODdhM2YiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJkdWxsYWhhdHRhLXN0cmVldHdyaXRlci02NzA4YjYxMi0wMDA4OTgyNWM5LTRkY2EzOCJ9.tB4k6SloJvNd2xs7s4F7XCX6p8XYNY11jml0f4c-qB4">Huly&reg;: <b>NN-6565</b></a></sub>

**Comment by thecodrr** [comment]
This has been extensively discussed before. We even put it up in the list of ideas on our roadmap to see how many people actually want this. Conclusion? It’s a bad idea.

1. Very few people actually want this or find this useful
2. There’s no contextual benefit to having notes shown in a grid as opposed to in a list. You’ll see exactly the same number of notes (give or take) and exactly the same information that’s already available in the headline and other elements on a note card.
3. Grid layout makes even less sense for side-by-side note taking which is a center point of Notesnook. Why?
4. It’s a preferential thing. There’s no actual improvement in productivity or UX because most of the time you look at only a few note cards at a time. Very rarely do you find things by scrolling. If you are having trouble finding something, maybe try searching. If search isn’t working for you then it needs to be improved.
5. It increases engineering and maintenance burden. This wouldn’t even be a point but layout is already hard as it is. Why make it more complex by adding more variations? There’s performance implications, UX implications, UI implications…its just not for Notesnook.

Hope this clears up everything.
