### ISSUE TITLE
Error when pasting local Image

### ISSUE THREAD

**Issue by PricacyPro0** [streetwriters/notesnook#6896]
### What happened?

I'm Pro Subscriber. 
Fedora Linux on latest Version. 
Notesnook is also on Latest Version. 

If you do these two things Notesnook will crash. 
Copy and paste image into Notesnook
Drag and Drop image into Notesnook

![Image](https://github.com/user-attachments/assets/a461d713-f52e-49e9-aa92-baa7416139d2)

It's a small 200kb .png Image, but happens also with every other image. 
The issue is propably that for some reason Notesnook can*t find the image, altough it shows it, because you can select and drop it. It recgonisez the image but can*t import it. 

When I manually used the "Select Image from disk" feature, for some reason it doesn*t show any other Folder or document then the Notesnook Folder, where Notesnook and its backup is safed. 

### Steps to reproduce the problem

Copy and paste image into Notesnook
Drag and Drop image into Notesnook

### Version

3.0.19-53a1e2c-desktop

### Platform/OS

Linux

### Relevant log output

```shell
Failed to load the image.
Error: Failed to load the image.
    at o.onerror (https://app.notesnook.com/assets/use-auto-updater-DO50gFwEm_Js.js:6:47845)
```

**Comment by chairmantheboring** [comment]
This is because of the default sandboxing rules in the flatpak package for Notesnook. It only has access to your Documents folder by default. You can change these rules using a tool called [flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal). You may want to create an issue in [the repository for the flatpak application](https://github.com/flathub/com.notesnook.Notesnook) so the maintainer is aware of this and can act accordingly (it isn't necessarily something the developers of the notesnook application can fix, it is a result of the flatpak sandbox).

I'm neither the maintainer for the flatpak package nor a developer of Notesnook, I am just giving you information on why it happens and what you can do about it.

**Comment by PricacyPro0** [comment]
Thanks a lot for the information.

Gesendet von Proton Mail für Android

-------- Ursprüngliche Nachricht --------
Am 18.11.24 08:45 um Moree schrieb :
