### ISSUE TITLE
OneNote Import Errors

### ISSUE THREAD

**Issue by 9808us** [streetwriters/notesnook#869]
I followed the link presented to send a bug report

![image](https://user-images.githubusercontent.com/38046064/188303426-2eef55fb-4da5-4339-a834-b7fab77ac7ad.png)

The import tool had errors and not all my notes where exported/imported from onenote to notesnook

**Comment by thecodrr** [comment]
Hi,

Unfortunately, these error can be safely ignored as they occur when a sectionGroup cannot be found (since you didnt create one).

If some of your notes are missing, unfortunately we can't do much because Microsoft sometimes refuses to share the notes via the OneNote API.

I am looking into if we can add support for OneNote backup files which will import all notes.

**Comment by brashesvoucher** [comment]
I don't know if this is helpful or not, but I've noticed that if I go and edit some notes that were previously not able to be imported, following editing, they are able to be imported.

**Comment by 9808us** [comment]
Thank you for the answers!
Is there a way to know which notes/sections could be the issue?

**Comment by thecodrr** [comment]
@9808us when an error comes the importer tells which note/section it is related to. However, if some notes are completely missing from the MS side we can't do much.
