### ISSUE TITLE
Save images when Notesnook Importer processes export files from other apps

### ISSUE THREAD

**Issue by 4132tester** [streetwriters/notesnook#877]
### What problem are you facing?

I'm trying to switch from Evernote to Notesnook. So, I've exported some of my old notes and after importing them to Notesnook it's appeared that images are lost. This is really frustrating, as makes the migration process with this re-capturing screenshots and repasting them a quite daunting and labour intensive task 

### What's the solution you'd like to see in Notesnook?

It would be great if images will remain in their places after the conversion and import process

**Comment by ammarahm-ed** [comment]
If the images are not imported, its probably a bug because attachment support is there already.

Maybe there's something up with your Notebooks in Evernote. Create a New Notebook with an note that has an image. Then export it.

If you still don't see an image, kindly share the enex file here of the test notebook so we can look into it and see what the issue is.

**Comment by 4132tester** [comment]
@ammarahm-ed  it worked with a new note! Thanks. Looks like it matters how you are adding an image to Evernote - doesn't matter anyway - not a Notesnoo's issue.
