### ISSUE TITLE
Error exporting from OneNote

### ISSUE THREAD

**Issue by gnumanx** [streetwriters/notesnook#967]
Trying to import the OneNote notes to notesnook I received this error with the encouragement to post the issue.
```
Your notes are ready for download
11 notes found
2 errors occured
1. Failed to get sectionGroup (original error: The specified resource ID does not exist.). (Request failed with status code: 404).
2. Failed to get sectionGroup (original error: The specified resource ID does not exist.). (Request failed with status code: 404).
```

**Comment by thecodrr** [comment]
That error can be ignored. It's not really a bug but an error that's produced because M$ doesn't expose the necessary information to know whether a Section Group exists for a Section or not. That's why we have to try and get a Section Group for each Section which results in these errors.

I think it'll be a good idea to just ignore them in the UI.
